>>> from django.contrib.auth.models import User
>>> user = User.objects.get(pk=3)
>>> user
<User: josejose>
>>> user.profile
<Profile: josejose>
>>> user.profile.description
'jose jose'
>>> user.profile.cards
<django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x000001AB07425820>
>>> user.profile.cards.all()
<QuerySet [<Card: first card>, <Card: Second card>]>
>>> user_cards=user.profile.cards.all()
>>> user_cards[0].name
'first card'
>>> user_cards[1].name
'Second card'
>>> user_cards[2].name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\00-Proyects\UTCH\ITI91m\glasmart\glasmart_webApp\venv\lib\site-packages\django\db\models\query.py", line 325, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range